# fly.toml app configuration file generated for 3d-embeddings on 2023-10-20T18:04:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "3d-embeddings"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
